/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PluginRouteImport } from './routes/plugin'
import { Route as PairRouteImport } from './routes/pair'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardUsageRouteImport } from './routes/dashboard/usage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRulesetsRouteImport } from './routes/dashboard/rulesets'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardKeysRouteImport } from './routes/dashboard/keys'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiMemoriesRouteImport } from './routes/api/memories'
import { Route as ApiCheckPatternRouteImport } from './routes/api/check-pattern'
import { Route as ApiBillingRouteImport } from './routes/api/billing'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminStripeRouteImport } from './routes/admin/stripe'
import { Route as AdminRulesetsRouteImport } from './routes/admin/rulesets'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as DashboardRulesetsIndexRouteImport } from './routes/dashboard/rulesets.index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects.index'
import { Route as ApiSessionsIndexRouteImport } from './routes/api/sessions/index'
import { Route as ApiRulesetsIndexRouteImport } from './routes/api/rulesets/index'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiKeysIndexRouteImport } from './routes/api/keys/index'
import { Route as DashboardRulesetsIdRouteImport } from './routes/dashboard/rulesets.$id'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard/projects.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeSkillCheckoutRouteImport } from './routes/api/stripe/skill-checkout'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiSkillVersionRouteImport } from './routes/api/skill/version'
import { Route as ApiSkillDownloadRouteImport } from './routes/api/skill/download'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions/$id'
import { Route as ApiRulesetsIdRouteImport } from './routes/api/rulesets/$id'
import { Route as ApiRulesIdRouteImport } from './routes/api/rules/$id'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiLicenseHeartbeatRouteImport } from './routes/api/license/heartbeat'
import { Route as ApiKeysIdRouteImport } from './routes/api/keys/$id'
import { Route as ApiAuthDeviceRouteImport } from './routes/api/auth/device'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsageRouteImport } from './routes/api/admin/usage'
import { Route as ApiAdminSystemRouteImport } from './routes/api/admin/system'
import { Route as ApiAdminStripeRouteImport } from './routes/api/admin/stripe'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminRulesetsRouteImport } from './routes/api/admin/rulesets'
import { Route as ApiAdminLogsRouteImport } from './routes/api/admin/logs'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiRulesetsRulesetIdRulesRouteImport } from './routes/api/rulesets/$rulesetId/rules'
import { Route as ApiProjectsProjectIdRulesetsRouteImport } from './routes/api/projects/$projectId/rulesets'
import { Route as ApiAuthDeviceTokenRouteImport } from './routes/api/auth/device/token'
import { Route as ApiAuthDevicePairRouteImport } from './routes/api/auth/device/pair'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiProjectsProjectIdRulesetsRulesetIdRouteImport } from './routes/api/projects/$projectId/rulesets/$rulesetId'
import { Route as ApiAdminUsersIdTierRouteImport } from './routes/api/admin/users/$id/tier'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginRoute = PluginRouteImport.update({
  id: '/plugin',
  path: '/plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesetsRoute = DashboardRulesetsRouteImport.update({
  id: '/rulesets',
  path: '/rulesets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesRoute = ApiMemoriesRouteImport.update({
  id: '/api/memories',
  path: '/api/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckPatternRoute = ApiCheckPatternRouteImport.update({
  id: '/api/check-pattern',
  path: '/api/check-pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStripeRoute = AdminStripeRouteImport.update({
  id: '/stripe',
  path: '/stripe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesetsRoute = AdminRulesetsRouteImport.update({
  id: '/rulesets',
  path: '/rulesets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardRulesetsIndexRoute = DashboardRulesetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRulesetsRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const ApiSessionsIndexRoute = ApiSessionsIndexRouteImport.update({
  id: '/api/sessions/',
  path: '/api/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRulesetsIndexRoute = ApiRulesetsIndexRouteImport.update({
  id: '/api/rulesets/',
  path: '/api/rulesets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIndexRoute = ApiKeysIndexRouteImport.update({
  id: '/api/keys/',
  path: '/api/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRulesetsIdRoute = DashboardRulesetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRulesetsRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeSkillCheckoutRoute = ApiStripeSkillCheckoutRouteImport.update({
  id: '/api/stripe/skill-checkout',
  path: '/api/stripe/skill-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillVersionRoute = ApiSkillVersionRouteImport.update({
  id: '/api/skill/version',
  path: '/api/skill/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillDownloadRoute = ApiSkillDownloadRouteImport.update({
  id: '/api/skill/download',
  path: '/api/skill/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/api/sessions/$id',
  path: '/api/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRulesetsIdRoute = ApiRulesetsIdRouteImport.update({
  id: '/api/rulesets/$id',
  path: '/api/rulesets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRulesIdRoute = ApiRulesIdRouteImport.update({
  id: '/api/rules/$id',
  path: '/api/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseHeartbeatRoute = ApiLicenseHeartbeatRouteImport.update({
  id: '/api/license/heartbeat',
  path: '/api/license/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIdRoute = ApiKeysIdRouteImport.update({
  id: '/api/keys/$id',
  path: '/api/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDeviceRoute = ApiAuthDeviceRouteImport.update({
  id: '/api/auth/device',
  path: '/api/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsageRoute = ApiAdminUsageRouteImport.update({
  id: '/api/admin/usage',
  path: '/api/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSystemRoute = ApiAdminSystemRouteImport.update({
  id: '/api/admin/system',
  path: '/api/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStripeRoute = ApiAdminStripeRouteImport.update({
  id: '/api/admin/stripe',
  path: '/api/admin/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRulesetsRoute = ApiAdminRulesetsRouteImport.update({
  id: '/api/admin/rulesets',
  path: '/api/admin/rulesets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRulesetsRulesetIdRulesRoute =
  ApiRulesetsRulesetIdRulesRouteImport.update({
    id: '/api/rulesets/$rulesetId/rules',
    path: '/api/rulesets/$rulesetId/rules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdRulesetsRoute =
  ApiProjectsProjectIdRulesetsRouteImport.update({
    id: '/api/projects/$projectId/rulesets',
    path: '/api/projects/$projectId/rulesets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDeviceTokenRoute = ApiAuthDeviceTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ApiAuthDeviceRoute,
} as any)
const ApiAuthDevicePairRoute = ApiAuthDevicePairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => ApiAuthDeviceRoute,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/api/admin/users/$id',
  path: '/api/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRulesetsRulesetIdRoute =
  ApiProjectsProjectIdRulesetsRulesetIdRouteImport.update({
    id: '/$rulesetId',
    path: '/$rulesetId',
    getParentRoute: () => ApiProjectsProjectIdRulesetsRoute,
  } as any)
const ApiAdminUsersIdTierRoute = ApiAdminUsersIdTierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/plugin': typeof PluginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/rulesets': typeof AdminRulesetsRoute
  '/admin/stripe': typeof AdminStripeRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/billing': typeof ApiBillingRoute
  '/api/check-pattern': typeof ApiCheckPatternRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/usage': typeof ApiUsageRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/rulesets': typeof DashboardRulesetsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/rulesets': typeof ApiAdminRulesetsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/stripe': typeof ApiAdminStripeRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device': typeof ApiAuthDeviceRouteWithChildren
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/license/heartbeat': typeof ApiLicenseHeartbeatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/rules/$id': typeof ApiRulesIdRoute
  '/api/rulesets/$id': typeof ApiRulesetsIdRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/api/skill/download': typeof ApiSkillDownloadRoute
  '/api/skill/version': typeof ApiSkillVersionRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/skill-checkout': typeof ApiStripeSkillCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/rulesets/$id': typeof DashboardRulesetsIdRoute
  '/api/keys/': typeof ApiKeysIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/rulesets/': typeof ApiRulesetsIndexRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/rulesets/': typeof DashboardRulesetsIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/auth/device/pair': typeof ApiAuthDevicePairRoute
  '/api/auth/device/token': typeof ApiAuthDeviceTokenRoute
  '/api/projects/$projectId/rulesets': typeof ApiProjectsProjectIdRulesetsRouteWithChildren
  '/api/rulesets/$rulesetId/rules': typeof ApiRulesetsRulesetIdRulesRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/users/$id/tier': typeof ApiAdminUsersIdTierRoute
  '/api/projects/$projectId/rulesets/$rulesetId': typeof ApiProjectsProjectIdRulesetsRulesetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/plugin': typeof PluginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/rulesets': typeof AdminRulesetsRoute
  '/admin/stripe': typeof AdminStripeRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/billing': typeof ApiBillingRoute
  '/api/check-pattern': typeof ApiCheckPatternRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/usage': typeof ApiUsageRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/rulesets': typeof ApiAdminRulesetsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/stripe': typeof ApiAdminStripeRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device': typeof ApiAuthDeviceRouteWithChildren
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/license/heartbeat': typeof ApiLicenseHeartbeatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/rules/$id': typeof ApiRulesIdRoute
  '/api/rulesets/$id': typeof ApiRulesetsIdRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/api/skill/download': typeof ApiSkillDownloadRoute
  '/api/skill/version': typeof ApiSkillVersionRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/skill-checkout': typeof ApiStripeSkillCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/rulesets/$id': typeof DashboardRulesetsIdRoute
  '/api/keys': typeof ApiKeysIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/rulesets': typeof ApiRulesetsIndexRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/rulesets': typeof DashboardRulesetsIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/auth/device/pair': typeof ApiAuthDevicePairRoute
  '/api/auth/device/token': typeof ApiAuthDeviceTokenRoute
  '/api/projects/$projectId/rulesets': typeof ApiProjectsProjectIdRulesetsRouteWithChildren
  '/api/rulesets/$rulesetId/rules': typeof ApiRulesetsRulesetIdRulesRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/users/$id/tier': typeof ApiAdminUsersIdTierRoute
  '/api/projects/$projectId/rulesets/$rulesetId': typeof ApiProjectsProjectIdRulesetsRulesetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/plugin': typeof PluginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/rulesets': typeof AdminRulesetsRoute
  '/admin/stripe': typeof AdminStripeRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/billing': typeof ApiBillingRoute
  '/api/check-pattern': typeof ApiCheckPatternRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/usage': typeof ApiUsageRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/rulesets': typeof DashboardRulesetsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/rulesets': typeof ApiAdminRulesetsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/stripe': typeof ApiAdminStripeRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device': typeof ApiAuthDeviceRouteWithChildren
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/license/heartbeat': typeof ApiLicenseHeartbeatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/rules/$id': typeof ApiRulesIdRoute
  '/api/rulesets/$id': typeof ApiRulesetsIdRoute
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/api/skill/download': typeof ApiSkillDownloadRoute
  '/api/skill/version': typeof ApiSkillVersionRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/skill-checkout': typeof ApiStripeSkillCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/rulesets/$id': typeof DashboardRulesetsIdRoute
  '/api/keys/': typeof ApiKeysIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/rulesets/': typeof ApiRulesetsIndexRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/rulesets/': typeof DashboardRulesetsIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/auth/device/pair': typeof ApiAuthDevicePairRoute
  '/api/auth/device/token': typeof ApiAuthDeviceTokenRoute
  '/api/projects/$projectId/rulesets': typeof ApiProjectsProjectIdRulesetsRouteWithChildren
  '/api/rulesets/$rulesetId/rules': typeof ApiRulesetsRulesetIdRulesRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/users/$id/tier': typeof ApiAdminUsersIdTierRoute
  '/api/projects/$projectId/rulesets/$rulesetId': typeof ApiProjectsProjectIdRulesetsRulesetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pair'
    | '/plugin'
    | '/privacy'
    | '/terms'
    | '/admin/logs'
    | '/admin/rulesets'
    | '/admin/stripe'
    | '/admin/system'
    | '/admin/usage'
    | '/admin/users'
    | '/api/billing'
    | '/api/check-pattern'
    | '/api/memories'
    | '/api/search'
    | '/api/usage'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/projects'
    | '/dashboard/rulesets'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$id'
    | '/api/admin/logs'
    | '/api/admin/rulesets'
    | '/api/admin/stats'
    | '/api/admin/stripe'
    | '/api/admin/system'
    | '/api/admin/usage'
    | '/api/auth/$'
    | '/api/auth/device'
    | '/api/keys/$id'
    | '/api/license/heartbeat'
    | '/api/projects/$id'
    | '/api/rules/$id'
    | '/api/rulesets/$id'
    | '/api/sessions/$id'
    | '/api/skill/download'
    | '/api/skill/version'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/skill-checkout'
    | '/api/stripe/webhook'
    | '/dashboard/projects/$id'
    | '/dashboard/rulesets/$id'
    | '/api/keys/'
    | '/api/projects/'
    | '/api/rulesets/'
    | '/api/sessions/'
    | '/dashboard/projects/'
    | '/dashboard/rulesets/'
    | '/api/admin/users/$id'
    | '/api/auth/device/pair'
    | '/api/auth/device/token'
    | '/api/projects/$projectId/rulesets'
    | '/api/rulesets/$rulesetId/rules'
    | '/api/admin/users/'
    | '/api/admin/users/$id/tier'
    | '/api/projects/$projectId/rulesets/$rulesetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pair'
    | '/plugin'
    | '/privacy'
    | '/terms'
    | '/admin/logs'
    | '/admin/rulesets'
    | '/admin/stripe'
    | '/admin/system'
    | '/admin/usage'
    | '/admin/users'
    | '/api/billing'
    | '/api/check-pattern'
    | '/api/memories'
    | '/api/search'
    | '/api/usage'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/admin'
    | '/dashboard'
    | '/admin/users/$id'
    | '/api/admin/logs'
    | '/api/admin/rulesets'
    | '/api/admin/stats'
    | '/api/admin/stripe'
    | '/api/admin/system'
    | '/api/admin/usage'
    | '/api/auth/$'
    | '/api/auth/device'
    | '/api/keys/$id'
    | '/api/license/heartbeat'
    | '/api/projects/$id'
    | '/api/rules/$id'
    | '/api/rulesets/$id'
    | '/api/sessions/$id'
    | '/api/skill/download'
    | '/api/skill/version'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/skill-checkout'
    | '/api/stripe/webhook'
    | '/dashboard/projects/$id'
    | '/dashboard/rulesets/$id'
    | '/api/keys'
    | '/api/projects'
    | '/api/rulesets'
    | '/api/sessions'
    | '/dashboard/projects'
    | '/dashboard/rulesets'
    | '/api/admin/users/$id'
    | '/api/auth/device/pair'
    | '/api/auth/device/token'
    | '/api/projects/$projectId/rulesets'
    | '/api/rulesets/$rulesetId/rules'
    | '/api/admin/users'
    | '/api/admin/users/$id/tier'
    | '/api/projects/$projectId/rulesets/$rulesetId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/pair'
    | '/plugin'
    | '/privacy'
    | '/terms'
    | '/admin/logs'
    | '/admin/rulesets'
    | '/admin/stripe'
    | '/admin/system'
    | '/admin/usage'
    | '/admin/users'
    | '/api/billing'
    | '/api/check-pattern'
    | '/api/memories'
    | '/api/search'
    | '/api/usage'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/projects'
    | '/dashboard/rulesets'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$id'
    | '/api/admin/logs'
    | '/api/admin/rulesets'
    | '/api/admin/stats'
    | '/api/admin/stripe'
    | '/api/admin/system'
    | '/api/admin/usage'
    | '/api/auth/$'
    | '/api/auth/device'
    | '/api/keys/$id'
    | '/api/license/heartbeat'
    | '/api/projects/$id'
    | '/api/rules/$id'
    | '/api/rulesets/$id'
    | '/api/sessions/$id'
    | '/api/skill/download'
    | '/api/skill/version'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/skill-checkout'
    | '/api/stripe/webhook'
    | '/dashboard/projects/$id'
    | '/dashboard/rulesets/$id'
    | '/api/keys/'
    | '/api/projects/'
    | '/api/rulesets/'
    | '/api/sessions/'
    | '/dashboard/projects/'
    | '/dashboard/rulesets/'
    | '/api/admin/users/$id'
    | '/api/auth/device/pair'
    | '/api/auth/device/token'
    | '/api/projects/$projectId/rulesets'
    | '/api/rulesets/$rulesetId/rules'
    | '/api/admin/users/'
    | '/api/admin/users/$id/tier'
    | '/api/projects/$projectId/rulesets/$rulesetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PairRoute: typeof PairRoute
  PluginRoute: typeof PluginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiCheckPatternRoute: typeof ApiCheckPatternRoute
  ApiMemoriesRoute: typeof ApiMemoriesRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminRulesetsRoute: typeof ApiAdminRulesetsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminStripeRoute: typeof ApiAdminStripeRoute
  ApiAdminSystemRoute: typeof ApiAdminSystemRoute
  ApiAdminUsageRoute: typeof ApiAdminUsageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDeviceRoute: typeof ApiAuthDeviceRouteWithChildren
  ApiKeysIdRoute: typeof ApiKeysIdRoute
  ApiLicenseHeartbeatRoute: typeof ApiLicenseHeartbeatRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
  ApiRulesIdRoute: typeof ApiRulesIdRoute
  ApiRulesetsIdRoute: typeof ApiRulesetsIdRoute
  ApiSessionsIdRoute: typeof ApiSessionsIdRoute
  ApiSkillDownloadRoute: typeof ApiSkillDownloadRoute
  ApiSkillVersionRoute: typeof ApiSkillVersionRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeSkillCheckoutRoute: typeof ApiStripeSkillCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiRulesetsIndexRoute: typeof ApiRulesetsIndexRoute
  ApiSessionsIndexRoute: typeof ApiSessionsIndexRoute
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
  ApiProjectsProjectIdRulesetsRoute: typeof ApiProjectsProjectIdRulesetsRouteWithChildren
  ApiRulesetsRulesetIdRulesRoute: typeof ApiRulesetsRulesetIdRulesRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin': {
      id: '/plugin'
      path: '/plugin'
      fullPath: '/plugin'
      preLoaderRoute: typeof PluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rulesets': {
      id: '/dashboard/rulesets'
      path: '/rulesets'
      fullPath: '/dashboard/rulesets'
      preLoaderRoute: typeof DashboardRulesetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories': {
      id: '/api/memories'
      path: '/api/memories'
      fullPath: '/api/memories'
      preLoaderRoute: typeof ApiMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-pattern': {
      id: '/api/check-pattern'
      path: '/api/check-pattern'
      fullPath: '/api/check-pattern'
      preLoaderRoute: typeof ApiCheckPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stripe': {
      id: '/admin/stripe'
      path: '/stripe'
      fullPath: '/admin/stripe'
      preLoaderRoute: typeof AdminStripeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rulesets': {
      id: '/admin/rulesets'
      path: '/rulesets'
      fullPath: '/admin/rulesets'
      preLoaderRoute: typeof AdminRulesetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/rulesets/': {
      id: '/dashboard/rulesets/'
      path: '/'
      fullPath: '/dashboard/rulesets/'
      preLoaderRoute: typeof DashboardRulesetsIndexRouteImport
      parentRoute: typeof DashboardRulesetsRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/api/sessions/': {
      id: '/api/sessions/'
      path: '/api/sessions'
      fullPath: '/api/sessions/'
      preLoaderRoute: typeof ApiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rulesets/': {
      id: '/api/rulesets/'
      path: '/api/rulesets'
      fullPath: '/api/rulesets/'
      preLoaderRoute: typeof ApiRulesetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/': {
      id: '/api/keys/'
      path: '/api/keys'
      fullPath: '/api/keys/'
      preLoaderRoute: typeof ApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rulesets/$id': {
      id: '/dashboard/rulesets/$id'
      path: '/$id'
      fullPath: '/dashboard/rulesets/$id'
      preLoaderRoute: typeof DashboardRulesetsIdRouteImport
      parentRoute: typeof DashboardRulesetsRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/skill-checkout': {
      id: '/api/stripe/skill-checkout'
      path: '/api/stripe/skill-checkout'
      fullPath: '/api/stripe/skill-checkout'
      preLoaderRoute: typeof ApiStripeSkillCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill/version': {
      id: '/api/skill/version'
      path: '/api/skill/version'
      fullPath: '/api/skill/version'
      preLoaderRoute: typeof ApiSkillVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill/download': {
      id: '/api/skill/download'
      path: '/api/skill/download'
      fullPath: '/api/skill/download'
      preLoaderRoute: typeof ApiSkillDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/api/sessions/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rulesets/$id': {
      id: '/api/rulesets/$id'
      path: '/api/rulesets/$id'
      fullPath: '/api/rulesets/$id'
      preLoaderRoute: typeof ApiRulesetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rules/$id': {
      id: '/api/rules/$id'
      path: '/api/rules/$id'
      fullPath: '/api/rules/$id'
      preLoaderRoute: typeof ApiRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/heartbeat': {
      id: '/api/license/heartbeat'
      path: '/api/license/heartbeat'
      fullPath: '/api/license/heartbeat'
      preLoaderRoute: typeof ApiLicenseHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/$id': {
      id: '/api/keys/$id'
      path: '/api/keys/$id'
      fullPath: '/api/keys/$id'
      preLoaderRoute: typeof ApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/device': {
      id: '/api/auth/device'
      path: '/api/auth/device'
      fullPath: '/api/auth/device'
      preLoaderRoute: typeof ApiAuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/usage': {
      id: '/api/admin/usage'
      path: '/api/admin/usage'
      fullPath: '/api/admin/usage'
      preLoaderRoute: typeof ApiAdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/system': {
      id: '/api/admin/system'
      path: '/api/admin/system'
      fullPath: '/api/admin/system'
      preLoaderRoute: typeof ApiAdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stripe': {
      id: '/api/admin/stripe'
      path: '/api/admin/stripe'
      fullPath: '/api/admin/stripe'
      preLoaderRoute: typeof ApiAdminStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rulesets': {
      id: '/api/admin/rulesets'
      path: '/api/admin/rulesets'
      fullPath: '/api/admin/rulesets'
      preLoaderRoute: typeof ApiAdminRulesetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users/'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rulesets/$rulesetId/rules': {
      id: '/api/rulesets/$rulesetId/rules'
      path: '/api/rulesets/$rulesetId/rules'
      fullPath: '/api/rulesets/$rulesetId/rules'
      preLoaderRoute: typeof ApiRulesetsRulesetIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/rulesets': {
      id: '/api/projects/$projectId/rulesets'
      path: '/api/projects/$projectId/rulesets'
      fullPath: '/api/projects/$projectId/rulesets'
      preLoaderRoute: typeof ApiProjectsProjectIdRulesetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/device/token': {
      id: '/api/auth/device/token'
      path: '/token'
      fullPath: '/api/auth/device/token'
      preLoaderRoute: typeof ApiAuthDeviceTokenRouteImport
      parentRoute: typeof ApiAuthDeviceRoute
    }
    '/api/auth/device/pair': {
      id: '/api/auth/device/pair'
      path: '/pair'
      fullPath: '/api/auth/device/pair'
      preLoaderRoute: typeof ApiAuthDevicePairRouteImport
      parentRoute: typeof ApiAuthDeviceRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/rulesets/$rulesetId': {
      id: '/api/projects/$projectId/rulesets/$rulesetId'
      path: '/$rulesetId'
      fullPath: '/api/projects/$projectId/rulesets/$rulesetId'
      preLoaderRoute: typeof ApiProjectsProjectIdRulesetsRulesetIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdRulesetsRoute
    }
    '/api/admin/users/$id/tier': {
      id: '/api/admin/users/$id/tier'
      path: '/tier'
      fullPath: '/api/admin/users/$id/tier'
      preLoaderRoute: typeof ApiAdminUsersIdTierRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRulesetsRoute: typeof AdminRulesetsRoute
  AdminStripeRoute: typeof AdminStripeRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminRulesetsRoute: AdminRulesetsRoute,
  AdminStripeRoute: AdminStripeRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardProjectsRouteChildren {
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRulesetsRouteChildren {
  DashboardRulesetsIdRoute: typeof DashboardRulesetsIdRoute
  DashboardRulesetsIndexRoute: typeof DashboardRulesetsIndexRoute
}

const DashboardRulesetsRouteChildren: DashboardRulesetsRouteChildren = {
  DashboardRulesetsIdRoute: DashboardRulesetsIdRoute,
  DashboardRulesetsIndexRoute: DashboardRulesetsIndexRoute,
}

const DashboardRulesetsRouteWithChildren =
  DashboardRulesetsRoute._addFileChildren(DashboardRulesetsRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardRulesetsRoute: typeof DashboardRulesetsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardRulesetsRoute: DashboardRulesetsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAuthDeviceRouteChildren {
  ApiAuthDevicePairRoute: typeof ApiAuthDevicePairRoute
  ApiAuthDeviceTokenRoute: typeof ApiAuthDeviceTokenRoute
}

const ApiAuthDeviceRouteChildren: ApiAuthDeviceRouteChildren = {
  ApiAuthDevicePairRoute: ApiAuthDevicePairRoute,
  ApiAuthDeviceTokenRoute: ApiAuthDeviceTokenRoute,
}

const ApiAuthDeviceRouteWithChildren = ApiAuthDeviceRoute._addFileChildren(
  ApiAuthDeviceRouteChildren,
)

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdTierRoute: typeof ApiAdminUsersIdTierRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdTierRoute: ApiAdminUsersIdTierRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiProjectsProjectIdRulesetsRouteChildren {
  ApiProjectsProjectIdRulesetsRulesetIdRoute: typeof ApiProjectsProjectIdRulesetsRulesetIdRoute
}

const ApiProjectsProjectIdRulesetsRouteChildren: ApiProjectsProjectIdRulesetsRouteChildren =
  {
    ApiProjectsProjectIdRulesetsRulesetIdRoute:
      ApiProjectsProjectIdRulesetsRulesetIdRoute,
  }

const ApiProjectsProjectIdRulesetsRouteWithChildren =
  ApiProjectsProjectIdRulesetsRoute._addFileChildren(
    ApiProjectsProjectIdRulesetsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PairRoute: PairRoute,
  PluginRoute: PluginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiCheckPatternRoute: ApiCheckPatternRoute,
  ApiMemoriesRoute: ApiMemoriesRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminRulesetsRoute: ApiAdminRulesetsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminStripeRoute: ApiAdminStripeRoute,
  ApiAdminSystemRoute: ApiAdminSystemRoute,
  ApiAdminUsageRoute: ApiAdminUsageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDeviceRoute: ApiAuthDeviceRouteWithChildren,
  ApiKeysIdRoute: ApiKeysIdRoute,
  ApiLicenseHeartbeatRoute: ApiLicenseHeartbeatRoute,
  ApiProjectsIdRoute: ApiProjectsIdRoute,
  ApiRulesIdRoute: ApiRulesIdRoute,
  ApiRulesetsIdRoute: ApiRulesetsIdRoute,
  ApiSessionsIdRoute: ApiSessionsIdRoute,
  ApiSkillDownloadRoute: ApiSkillDownloadRoute,
  ApiSkillVersionRoute: ApiSkillVersionRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeSkillCheckoutRoute: ApiStripeSkillCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiKeysIndexRoute: ApiKeysIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiRulesetsIndexRoute: ApiRulesetsIndexRoute,
  ApiSessionsIndexRoute: ApiSessionsIndexRoute,
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
  ApiProjectsProjectIdRulesetsRoute:
    ApiProjectsProjectIdRulesetsRouteWithChildren,
  ApiRulesetsRulesetIdRulesRoute: ApiRulesetsRulesetIdRulesRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
